### ISSUE TITLE
翻译修正

### ISSUE THREAD

**Issue by HyperLife1119** [ng-docs/angular-en#1]
- [ ] [阅读而不跟踪依赖关系](https://angular-18.oss-cn-hangzhou.aliyuncs.com/guide/signals#reading-without-tracking-dependencies) -> 不跟踪依赖关系的读取
- [ ] [DI 体系](https://angular-18.oss-cn-hangzhou.aliyuncs.com/guide/di/dependency-injection-context#:~:text=%E4%BE%9D%E8%B5%96%E6%B3%A8%E5%85%A5%EF%BC%88DI%EF%BC%89-,%E4%BD%93%E7%B3%BB,-%E5%86%85%E9%83%A8%E4%BE%9D%E8%B5%96%E4%BA%8E) -> DI 系统
```[tasklist]
### Tasks
- [x] 检查 read 错翻为阅读的情况
```
